import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F0F8F0',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#ECF0F1',
    },
    headerBackButton: {
        width: 44,
        height: 44,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#2C3E50',
        fontFamily: 'Nunito_700Bold',
    },
    headerSpacer: {
        width: 44,
    },
    content: {
        flex: 1,
        paddingHorizontal: 16,
        paddingTop: 12,
    },
    scroll: {
        width: '100%',
        paddingHorizontal: 0,
    },
    notificationRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        paddingVertical: 10,
        paddingHorizontal: 12,
        marginBottom: 10,
        shadowColor: '#000',
        shadowOpacity: 0.03,
        shadowRadius: 3,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#F3F4F6',
        borderLeftWidth: 6,
    },
    statusIconWrap: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
    },
    plantName: {
        fontSize: 16,
        fontWeight: 'bold',
        fontFamily: 'Nunito_700Bold',
    },
    unreadText: {
        fontWeight: 'bold',
        color: '#111827',
        fontFamily: 'Nunito_700Bold',
    },
    unreadDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#3B82F6',
        marginLeft: 8,
    },
    unreadDotSmall: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#3B82F6',
        marginLeft: 6,
        marginTop: 2,
    },
    statusText: {
        fontSize: 12,
        color: '#6B7280',
        marginTop: 2,
        fontFamily: 'Nunito_400Regular',
    },
    statusPill: {
        borderWidth: 1,
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 999,
    },
    statusPillFilled: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 999,
    },
    statusPillText: {
        fontSize: 11,
        fontWeight: '700',
        fontFamily: 'Nunito_700Bold',
    },
    statusPillTextInverse: {
        fontSize: 11,
        fontWeight: '700',
        color: '#FFFFFF',
        fontFamily: 'Nunito_700Bold',
    },
    infoText: {
        fontSize: 12,
        color: '#374151',
        marginTop: 2,
        fontFamily: 'Nunito_400Regular',
    },
    message: {
        fontSize: 12,
        color: '#374151',
        marginTop: 2,
        fontFamily: 'Nunito_400Regular',
    },
    placeholder: {
        fontSize: 16,
        color: '#6B7280',
        marginTop: 32,
        fontFamily: 'Nunito_400Regular',
    },
    error: {
        color: '#EF4444',
        fontSize: 16,
        marginTop: 32,
        fontFamily: 'Nunito_500Medium',
    },
    emptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'flex-start',
        marginTop: 80, // Moves the content down
    },
    emptyStateText: {
        fontSize: 16,
        color: '#6B7280',
        marginTop: 8,
        fontFamily: 'Nunito_400Regular',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 40,
    },
    loadingSpinner: {
        marginBottom: 24,
        // Add rotation animation
        transform: [{ rotate: '0deg' }],
    },
    loadingTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#16A34A',
        marginBottom: 8,
        fontFamily: 'Nunito_700Bold',
    },
    loadingMessage: {
        fontSize: 16,
        color: '#6B7280',
        textAlign: 'center',
        paddingHorizontal: 32,
        fontFamily: 'Nunito_400Regular',
        marginBottom: 8,
    },
    loadingProgress: {
        fontSize: 14,
        color: '#4CAF50',
        fontWeight: '600',
        fontFamily: 'Nunito_600SemiBold',
    },
    loadingText: {
        fontSize: 16,
        color: '#16A34A',
        marginTop: 12,
        fontFamily: 'Nunito_500Medium',
    },
    emptyContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 40,
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 24,
        marginHorizontal: 16,
        borderWidth: 1,
        borderColor: '#F3F4F6',
    },
    emptyTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#374151',
        marginTop: 16,
        marginBottom: 8,
        fontFamily: 'Nunito_700Bold',
    },
    emptyMessage: {
        fontSize: 16,
        color: '#6B7280',
        textAlign: 'center',
        paddingHorizontal: 32,
        fontFamily: 'Nunito_400Regular',
    },
}); 