import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F0F8F0',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#ECF0F1',
    },
    backButton: {
        padding: 4,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#2C3E50',
    },
    headerSpacer: {
        width: 32,
    },
    content: {
        flex: 1,
        paddingHorizontal: 16,
    },
    section: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        marginVertical: 8,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 8,
    },
    sectionSubtitle: {
        fontSize: 14,
        color: '#95A5A6',
        marginBottom: 16,
        fontStyle: 'italic',
    },
    plantTypeGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    plantTypeCard: {
        width: '30%',
        alignItems: 'center',
        padding: 12,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#ECF0F1',
        backgroundColor: '#F8F9FA',
        marginBottom: 12,
    },
    selectedPlantType: {
        borderColor: '#3498DB',
        backgroundColor: '#EBF8FF',
    },
    plantTypeImage: {
        width: 60,
        height: 60,
        resizeMode: 'cover',
        borderRadius: 8,
        marginBottom: 8,
    },
    plantTypeText: {
        fontSize: 12,
        fontWeight: '500',
        color: '#7F8C8D',
        textAlign: 'center',
    },
    selectedPlantTypeText: {
        color: '#3498DB',
        fontWeight: '600',
    },
    skipContainer: {
        width: 60,
        height: 60,
        borderRadius: 8,
        backgroundColor: '#F1F3F4',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 8,
    },
    inputGroup: {
        marginBottom: 20,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 8,
    },
    textInput: {
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 12,
        fontSize: 16,
        color: '#2C3E50',
        backgroundColor: '#FFFFFF',
    },
    inputHint: {
        fontSize: 12,
        color: '#95A5A6',
        marginTop: 4,
        fontStyle: 'italic',
    },
    frequencyGrid: {
        marginTop: 8,
    },
    frequencyCard: {
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        backgroundColor: '#F8F9FA',
        marginBottom: 8,
    },
    selectedFrequency: {
        borderColor: '#3498DB',
        backgroundColor: '#EBF8FF',
    },
    frequencyName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 2,
    },
    frequencyDescription: {
        fontSize: 12,
        color: '#7F8C8D',
    },
    selectedFrequencyText: {
        color: '#3498DB',
    },
    submitContainer: {
        paddingVertical: 20,
    },
    submitButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#3498DB',
        paddingVertical: 16,
        borderRadius: 12,
        shadowColor: '#3498DB',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    submitButtonDisabled: {
        backgroundColor: '#BDC3C7',
        shadowOpacity: 0.1,
    },
    submitButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 8,
    },
    connectionWarning: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FEE2E2',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#FCA5A5',
    },
    connectionWarningText: {
        color: '#E74C3C',
        fontSize: 14,
        fontWeight: '500',
        marginLeft: 8,
    },
    offlineMessage: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: '#EBF8FF',
        padding: 16,
        borderRadius: 8,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#BEE3F8',
    },
    offlineMessageText: {
        color: '#2B6CB0',
        fontSize: 14,
        lineHeight: 20,
        marginLeft: 12,
        flex: 1,
    },
    textInputDisabled: {
        backgroundColor: '#F7FAFC',
        color: '#A0AEC0',
    },
}); 