import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#ECF0F1',
    },
    backButton: {
        padding: 4,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#2C3E50',
        fontFamily: 'Nunito_600SemiBold',
    },
    settingsButton: {
        padding: 4,
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 16,
        fontSize: 16,
        color: '#7F8C8D',
        fontFamily: 'Nunito_500Medium',
    },
    gardenInfoCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        marginTop: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    gardenHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    gardenTitleContainer: {
        marginLeft: 16,
        flex: 1,
    },
    gardenTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#2C3E50',
        fontFamily: 'Nunito_700Bold',
    },
    gardenSubtitle: {
        fontSize: 14,
        color: '#7F8C8D',
        marginTop: 4,
        fontFamily: 'Nunito_400Regular',
    },
    inviteCodeSection: {
        borderTopWidth: 1,
        borderTopColor: '#ECF0F1',
        paddingTop: 20,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 12,
        fontFamily: 'Nunito_600SemiBold',
    },
    inviteCodeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#F8F9FA',
        borderRadius: 8,
        padding: 12,
    },
    inviteCode: {
        fontSize: 18,
        fontWeight: '700',
        color: '#4CAF50',
        fontFamily: 'Nunito_700Bold',
        letterSpacing: 2,
    },
    inviteCodeActions: {
        flexDirection: 'row',
        gap: 8,
    },
    inviteCodeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#4CAF50',
    },
    inviteCodeButtonText: {
        marginLeft: 4,
        fontSize: 12,
        fontWeight: '600',
        color: '#4CAF50',
        fontFamily: 'Nunito_600SemiBold',
    },
    quickActionsSection: {
        marginTop: 24,
    },
    quickActionsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
    },
    quickActionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        alignItems: 'center',
        flex: 1,
        minWidth: '30%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    quickActionText: {
        marginTop: 8,
        fontSize: 14,
        fontWeight: '600',
        color: '#2C3E50',
        textAlign: 'center',
        fontFamily: 'Nunito_600SemiBold',
    },
    membersSection: {
        marginTop: 24,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    manageButton: {
        fontSize: 14,
        fontWeight: '600',
        color: '#4CAF50',
        fontFamily: 'Nunito_600SemiBold',
    },
    emptyMembers: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 40,
        alignItems: 'center',
    },
    emptyMembersText: {
        marginTop: 12,
        fontSize: 16,
        color: '#7F8C8D',
        fontFamily: 'Nunito_400Regular',
    },
    membersList: {
        gap: 8,
    },
    memberCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    memberInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    memberAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#4CAF50',
        justifyContent: 'center',
        alignItems: 'center',
    },
    memberDetails: {
        marginLeft: 12,
        flex: 1,
    },
    memberName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2C3E50',
        fontFamily: 'Nunito_600SemiBold',
    },
    memberRole: {
        fontSize: 14,
        color: '#7F8C8D',
        marginTop: 2,
        fontFamily: 'Nunito_400Regular',
    },
    memberJoined: {
        fontSize: 12,
        color: '#95A5A6',
        fontFamily: 'Nunito_400Regular',
    },
    dangerZone: {
        marginTop: 24,
        marginBottom: 40,
    },
    leaveButton: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#E74C3C',
    },
    leaveButtonText: {
        marginLeft: 8,
        fontSize: 16,
        fontWeight: '600',
        color: '#E74C3C',
        fontFamily: 'Nunito_600SemiBold',
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 24,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 8,
        elevation: 8,
    },
});

export default styles;
