import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F0F8F0',
  },
  header: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#ECF0F1',
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerLeft: {
    flex: 1,
  },
  appTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  appLogo: {
    width: 24,
    height: 28,
    marginRight: 8,
  },
  appTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2C3E50',
    fontFamily: 'Nunito_700Bold',
  },
  greeting: {
    fontSize: 16,
    fontWeight: '500',
    color: '#6B7280',
    marginBottom: 2,
    fontFamily: 'Nunito_500Medium',
  },
  subtitle: {
    fontSize: 14,
    color: '#95A5A6',
    fontFamily: 'Nunito_400Regular',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#2C3E50',
    fontFamily: 'Nunito_700Bold',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileButton: {
    padding: 4,
  },
  notificationsButton: {
    padding: 4,
    marginRight: 12,
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  notificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
    fontFamily: 'Nunito_700Bold',
  },
  logoutButton: {
    padding: 4,
  },
  connectionWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEE2E2',
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginHorizontal: 20,
    marginVertical: 10,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#E74C3C',
  },
  connectionWarningText: {
    color: '#E74C3C',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 8,
    fontFamily: 'Nunito_500Medium',
  },
  retryButton: {
    marginLeft: 'auto',
    paddingHorizontal: 12,
    paddingVertical: 4,
    backgroundColor: '#E74C3C',
    borderRadius: 4,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Nunito_600SemiBold',
  },
  plantsSection: {
    flex: 0.6,
    marginTop: 8,
    marginBottom: 16,
  },
  notificationsSection: {
    flex: 1,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 12,
    paddingHorizontal: 16,
    fontFamily: 'Nunito_500Medium',
  },
  titleSeparator: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 16,
    marginBottom: 12,
  },
  topImageContainer: {
    width: '100%',
    height: 200,
    overflow: 'hidden',
    position: 'relative',
  },
  topImage: {
    width: '100%',
    height: 480,
    position: 'absolute',
    top: 0,
    left: 0,
  },
  topImageBorder: {
    // No border radius
  },
  mainContentCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    marginTop: -32,
    paddingTop: 24,
    overflow: 'visible',
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    paddingBottom: 56, // Reduced to tighten space above bottom toolbar
  },
  articlesSection: {
    marginTop: 24,
    marginBottom: 12,
  },
  greetingContainer: {
    paddingLeft: 24,
    paddingBottom: 24,
    backgroundColor: 'rgba(255,255,255,0.0)',
  },
  topBar: {
    width: '100%',
    height: 38,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E0E0E0',
    zIndex: 10,
    elevation: 6,
    position: 'relative',
  },
  topBarLogo: {
    width: 35,
    height: 40,
    marginRight: 6,
    resizeMode: 'contain',
  },
  topBarTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1c7823',
    fontFamily: 'Nunito_700Bold',
  },
  greetingOverlay: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    width: '100%',
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
    paddingBottom: 48,
    paddingLeft: 24,
  },
  greetingWhite: {
    fontSize: 25,
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'Nunito_700Bold',
    textShadowColor: 'rgba(0,0,0,0.7)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 12,
    textAlign: 'left',
  },
  topBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  topBarNotification: {
    padding: 8,
    position: 'relative',
    marginRight: 12,
  },
  weatherRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 8,
  },
  weatherSubtitleContainer: {
    width: '38%',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  weatherCardContainer: {
    width: '60%',
    alignItems: 'flex-end',
  },
  weatherSubtitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
    fontFamily: 'Nunito_700Bold',
    textAlign: 'left',
    lineHeight: 24,
  },
  weatherCardFullWidth: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 8,
    marginHorizontal: 0,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  loadingCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    minWidth: 200,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#2C3E50',
    textAlign: 'center',
    fontFamily: 'Nunito_500Medium',
  },

  // Garden Status Banner Styles
  gardenStatusContainer: {
    marginHorizontal: 16,
    marginVertical: 12,
  },
  gardenActiveBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  gardenIconContainerActive: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F0FDF4',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#DCFCE7',
  },
  gardenInactiveBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  gardenIconContainerInactive: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFF7ED',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FFEDD5',
  },
  gardenInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  gardenStatusText: {
    color: '#2C3E50',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 10,
    fontFamily: 'Nunito_600SemiBold',
  },
  gardenStatusTextClickable: {
    color: '#1C7A23',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 10,
    fontFamily: 'Nunito_700Bold',
  },
  gardenSettingsButton: {
    padding: 8,
    backgroundColor: '#F0F9F0',
    borderRadius: 8,
  },

  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#2C3E50',
    textAlign: 'center',
    marginBottom: 24,
    fontFamily: 'Nunito_700Bold',
  },
  modalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    marginBottom: 12,
    gap: 12,
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#2C3E50',
    fontFamily: 'Nunito_500Medium',
  },
  cancelButton: {
    backgroundColor: '#FEF2F2',
    marginTop: 8,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#E74C3C',
    textAlign: 'center',
    fontFamily: 'Nunito_500Medium',
  },
});

export default styles; 