import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F0F8F0',
  },
  header: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#ECF0F1',
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerLeft: {
    flex: 1,
  },
  appTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  appLogo: {
    width: 24,
    height: 28,
    marginRight: 8,
  },
  appTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2C3E50',
    fontFamily: 'Nunito_700Bold',
  },
  greeting: {
    fontSize: 16,
    fontWeight: '500',
    color: '#6B7280',
    marginBottom: 2,
    fontFamily: 'Nunito_500Medium',
  },
  subtitle: {
    fontSize: 14,
    color: '#95A5A6',
    fontFamily: 'Nunito_400Regular',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#2C3E50',
    fontFamily: 'Nunito_700Bold',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileButton: {
    padding: 4,
  },
  notificationsButton: {
    padding: 4,
    marginRight: 12,
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  notificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
    fontFamily: 'Nunito_700Bold',
  },
  logoutButton: {
    padding: 4,
  },
  connectionWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FEE2E2',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#FCA5A5',
  },
  connectionWarningText: {
    color: '#E74C3C',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 8,
    fontFamily: 'Nunito_500Medium',
  },
  retryButton: {
    backgroundColor: '#E74C3C',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 6,
    marginLeft: 12,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'Nunito_700Bold',
  },
  plantsSection: {
    flex: 0.6,
    marginTop: 8,
    marginBottom: 16,
  },
  notificationsSection: {
    flex: 1,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 12,
    paddingHorizontal: 16,
    fontFamily: 'Nunito_500Medium',
  },
  titleSeparator: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 16,
    marginBottom: 12,
  },
  topImageContainer: {
    width: '100%',
    height: 200,
    overflow: 'hidden',
    position: 'relative',
  },
  topImage: {
    width: '100%',
    height: 480,
    position: 'absolute',
    top: 0,
    left: 0,
  },
  topImageBorder: {
    // No border radius
  },
  mainContentCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    marginTop: -32,
    paddingTop: 24,
    overflow: 'visible',
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    paddingBottom: 100, // Add bottom padding to ensure content is not cut off by bottom toolbar
  },
  articlesSection: {
    marginTop: 24,
    marginBottom: 24,
  },
  greetingContainer: {
    paddingLeft: 24,
    paddingBottom: 24,
    backgroundColor: 'rgba(255,255,255,0.0)',
  },
  topBar: {
    width: '100%',
    height: 38,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E0E0E0',
    zIndex: 10,
  },
  topBarLogo: {
    width: 35,
    height: 40,
    marginRight: 6,
    resizeMode: 'contain',
  },
  topBarTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1c7823',
    fontFamily: 'Nunito_700Bold',
  },
  greetingOverlay: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    width: '100%',
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
    paddingBottom: 48,
    paddingLeft: 24,
  },
  greetingWhite: {
    fontSize: 25,
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontFamily: 'Nunito_700Bold',
    textShadowColor: 'rgba(0,0,0,0.7)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 12,
    textAlign: 'left',
  },
  topBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  topBarNotification: {
    padding: 8,
    position: 'relative',
    marginRight: 12,
  },
  weatherRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 8,
  },
  weatherSubtitleContainer: {
    width: '38%',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  weatherCardContainer: {
    width: '60%',
    alignItems: 'flex-end',
  },
  weatherSubtitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
    fontFamily: 'Nunito_700Bold',
    textAlign: 'left',
    lineHeight: 24,
  },
  weatherCardFullWidth: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 8,
    marginHorizontal: 0,
  },
});

export default styles; 