import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#ECF0F1',
    },
    backButton: {
        padding: 4,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#2C3E50',
        fontFamily: 'Nunito_600SemiBold',
    },
    headerSpacer: {
        width: 32,
    },
    content: {
        flex: 1,
        paddingHorizontal: 20,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 16,
        fontSize: 16,
        color: '#7F8C8D',
        fontFamily: 'Nunito_500Medium',
    },
    section: {
        marginTop: 24,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 12,
        fontFamily: 'Nunito_600SemiBold',
    },
    settingCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    settingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#ECF0F1',
    },
    settingRowLast: {
        borderBottomWidth: 0,
    },
    settingLabel: {
        fontSize: 16,
        fontWeight: '500',
        color: '#2C3E50',
        fontFamily: 'Nunito_500Medium',
    },
    settingValue: {
        fontSize: 16,
        color: '#7F8C8D',
        fontFamily: 'Nunito_400Regular',
    },
    settingDescription: {
        fontSize: 14,
        color: '#95A5A6',
        marginTop: 4,
        fontFamily: 'Nunito_400Regular',
    },
    inputContainer: {
        marginTop: 8,
    },
    textInput: {
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 16,
        color: '#2C3E50',
        backgroundColor: '#FFFFFF',
        fontFamily: 'Nunito_400Regular',
    },
    saveButton: {
        backgroundColor: '#4CAF50',
        borderRadius: 8,
        paddingVertical: 12,
        alignItems: 'center',
        marginTop: 12,
    },
    saveButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Nunito_600SemiBold',
    },
    dangerZone: {
        marginTop: 32,
        marginBottom: 40,
    },
    dangerCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        borderWidth: 1,
        borderColor: '#E74C3C',
    },
    dangerTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#E74C3C',
        marginBottom: 8,
        fontFamily: 'Nunito_600SemiBold',
    },
    dangerDescription: {
        fontSize: 14,
        color: '#7F8C8D',
        marginBottom: 16,
        lineHeight: 20,
        fontFamily: 'Nunito_400Regular',
    },
    deleteButton: {
        backgroundColor: '#E74C3C',
        borderRadius: 8,
        paddingVertical: 16,
        alignItems: 'center',
    },
    deleteButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Nunito_600SemiBold',
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 24,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 8,
        elevation: 8,
    },
    roleIndicator: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginTop: 20,
        marginBottom: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    roleText: {
        marginLeft: 8,
        fontSize: 14,
        fontWeight: '600',
        color: '#7F8C8D',
        fontFamily: 'Nunito_600SemiBold',
    },
    roleTextAdmin: {
        color: '#4CAF50',
    },
    settingItem: {
        marginBottom: 20,
    },
    settingLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 8,
        fontFamily: 'Nunito_600SemiBold',
    },
    textInputDisabled: {
        backgroundColor: '#F8F9FA',
        color: '#7F8C8D',
    },
    settingHint: {
        fontSize: 14,
        color: '#95A5A6',
        marginTop: 4,
        fontFamily: 'Nunito_400Regular',
    },
    infoItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    infoLabel: {
        fontSize: 16,
        fontWeight: '500',
        color: '#7F8C8D',
        fontFamily: 'Nunito_500Medium',
    },
    infoValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#2C3E50',
        fontFamily: 'Nunito_600SemiBold',
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        paddingVertical: 16,
        marginBottom: 12,
    },
    resetButton: {
        backgroundColor: '#F8F9FA',
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    actionButtonDisabled: {
        backgroundColor: '#BDC3C7',
    },
    actionButtonText: {
        marginLeft: 8,
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
        fontFamily: 'Nunito_600SemiBold',
    },
    resetButtonText: {
        color: '#7F8C8D',
    },
    dangerButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 8,
        paddingVertical: 16,
        borderWidth: 1,
        borderColor: '#E74C3C',
    },
    dangerButtonText: {
        marginLeft: 8,
        fontSize: 16,
        fontWeight: '600',
        color: '#E74C3C',
        fontFamily: 'Nunito_600SemiBold',
    },
});

export default styles;
