import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F0F8F0',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#ECF0F1',
  },
  backButton: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2C3E50',
    fontFamily: 'Nunito_700Bold',
  },
  headerSpacer: {
    width: 32,
  },
  content: {
    flex: 1,
  },
  imageContainer: {
    width: '100%',
    height: 300,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    margin: 16,
    overflow: 'hidden',
    position: 'relative',
  },
  plantImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  infoOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    padding: 16,
    paddingTop: 20,
  },
  separator: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginBottom: 12,
  },
  infoLabel: {
    fontSize: 11,
    color: '#6B7280',
    marginBottom: 2,
    fontFamily: 'Nunito_700Bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  infoContainer: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    marginBottom: 8,
    marginHorizontal: 16,
    borderRadius: 16,
  },
  plantName: {
    fontSize: 24,
    fontWeight: '700',
    color: '#2C3E50',
    marginBottom: 4,
    fontFamily: 'Nunito_700Bold',
  },
  plantType: {
    fontSize: 16,
    color: '#7F8C8D',
    marginBottom: 8,
    fontFamily: 'Nunito_700Bold',
  },
  plantLocation: {
    fontSize: 14,
    color: '#95A5A6',
    marginBottom: 12,
    fontFamily: 'Nunito_700Bold',
  },
  statusContainer: {
    alignItems: 'flex-start',
  },
  statusIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  statusText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#2C3E50',
    fontFamily: 'Nunito_700Bold',
  },
  statsContainer: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    marginBottom: 8,
    marginHorizontal: 16,
    borderRadius: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 16,
    fontFamily: 'Nunito_700Bold',
  },
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statCard: {
    alignItems: 'center',
    flex: 1,
    paddingVertical: 12,
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    marginHorizontal: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#7F8C8D',
    marginTop: 8,
    marginBottom: 4,
    fontFamily: 'Nunito_700Bold',
  },
  statValue: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 2,
    fontFamily: 'Nunito_700Bold',
  },
  statStatus: {
    fontSize: 10,
    color: '#95A5A6',
    fontFamily: 'Nunito_700Bold',
  },
  actionsContainer: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    marginBottom: 8,
    marginHorizontal: 16,
    borderRadius: 16,
  },
  waterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4CAF50',
    paddingVertical: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  waterButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    marginLeft: 8,
    fontFamily: 'Nunito_700Bold',
  },
  scheduleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#4CAF50',
    paddingVertical: 12,
    borderRadius: 8,
  },
  scheduleButtonText: {
    color: '#4CAF50',
    fontWeight: '600',
    marginLeft: 8,
    fontFamily: 'Nunito_700Bold',
  },
  descriptionContainer: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    marginBottom: 20,
  },
  descriptionText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#7F8C8D',
    fontFamily: 'Nunito_700Bold',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    fontSize: 16,
    color: '#7F8C8D',
    fontFamily: 'Nunito_700Bold',
  },
}); 